language: node_js
node_js:
  - "6.10"
deploy:
  provider: s3
  skip_cleanup: true
  bucket: "lambda.js"
  region: eu-west-1
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  on:
    tags: true
