var ERROR_400 = "Tu petición no es válida, reformula la petición al servidor para obtner una respuesta válida.";
var ERROR_401 = "Tu session_id en aonSolutions no es válida, por favor vuelve a hacer login en aonSolutions.";
var ERROR_403 = "No tienes acceso a este servicio.";
var ERROR_404 = "El servicio solicitado no existe.";
var ERROR_405 = "El servicio solicitado no está activo.";
var ERROR_406 = "La petición realizada no es un JSON.";
var ERROR_410 = "El servicio ha sido eliminado de los servidores de aonSolutions."
var ERROR_429 = "Se han realizado demasiadas peticiones a los servicios en un periodo muy corto de tiempo."
var ERROR_500 = "Ha habido algún problema en los servidores de aonSolutions. Por favor, inténtelo más tarde."
var ERROR_503 = "El servicio no está disponible por razones de mantenimiento. Por favor, inténtelo más tarde."

exports.ERROR_400 = ERROR_400;
exports.ERROR_401 = ERROR_401;
exports.ERROR_402 = ERROR_402;
exports.ERROR_403 = ERROR_403;
exports.ERROR_404 = ERROR_404;
exports.ERROR_405 = ERROR_405;
exports.ERROR_406 = ERROR_406;
exports.ERROR_410 = ERROR_410;
exports.ERROR_429 = ERROR_429;
exports.ERROR_500 = ERROR_500;
exports.ERROR_503 = ERROR_503;
